export const BOM = [
  { line: 1, subsystem: 'Power', part: 'PMIC + Charger', mfg: 'TI', pn: 'BQ25895 (or BQ24074)', qty: 1, cost: 2.85, supplier: 'DigiKey', leadTime: '2 wk' },
  { line: 2, subsystem: 'Power', part: 'Battery Li-Po', mfg: 'Grepow', pn: '2,000\u20132,500 mAh', qty: 1, cost: 10, supplier: 'Vendor', leadTime: '4\u20136 wk' },
  { line: 3, subsystem: 'SoC', part: 'Qualcomm AR1+', mfg: 'Qualcomm', pn: 'AR1+', qty: 1, cost: 50, supplier: 'Rep / NDA', leadTime: '12\u201316 wk' },
  { line: 5, subsystem: 'Camera', part: 'Image Sensor', mfg: 'Framos', pn: 'FSM-IMX585', qty: 1, cost: 70, supplier: 'Distributor', leadTime: '8\u201312 wk' },
  { line: '5a', subsystem: 'Lens', part: 'Liquid Lens', mfg: 'Corning Varioptic', pn: 'A39N', qty: 1, cost: 58, supplier: 'Rep / NDA', leadTime: '10\u201314 wk' },
  { line: '5b', subsystem: 'Lens', part: 'Double Convex Lens', mfg: 'Edmund Optics', pn: '#47-359', qty: 1, cost: 22, supplier: 'Distributor', leadTime: '2\u20134 wk' },
  { line: '5c', subsystem: 'Lens', part: 'Aspheric Lens', mfg: 'Edmund Optics', pn: '#66-320', qty: 1, cost: 180, supplier: 'Distributor', leadTime: '4\u20136 wk' },
  { line: 6, subsystem: 'Display', part: 'Round AMOLED 1.8\u2033 480\u00d7480', mfg: 'Tianma', pn: 'MIPI-DSI module', qty: 1, cost: 20, supplier: 'Vendor', leadTime: '8\u201310 wk' },
  { line: 7, subsystem: 'Audio', part: 'Dual MEMS + ADC', mfg: 'Knowles / TI', pn: 'SPH0645 \u00d72 + TLV320ADC', qty: 1, cost: 4, supplier: 'DigiKey', leadTime: '2 wk' },
  { line: 8, subsystem: 'Connectivity', part: 'Wi-Fi/BLE module', mfg: 'Espressif/Murata', pn: 'ESP32-C6-MINI-1 or similar', qty: 1, cost: 3, supplier: 'Espressif', leadTime: '4\u20138 wk' },
  { line: 9, subsystem: 'Storage', part: 'microSD Slot + NOR Flash', mfg: 'Various', pn: 'W25Q64JV (NOR)', qty: 1, cost: 2, supplier: 'DigiKey', leadTime: '2 wk' },
  { line: 10, subsystem: 'Sensors', part: '6-Axis IMU', mfg: 'Bosch', pn: 'BMI270', qty: 1, cost: 2.5, supplier: 'DigiKey', leadTime: '2\u20134 wk' },
  { line: 11, subsystem: 'Sensors', part: 'Magnetometer', mfg: 'AKM', pn: 'AK09918C', qty: 1, cost: 1, supplier: 'Distributor', leadTime: '4\u20136 wk' },
  { line: 12, subsystem: 'Sensors', part: 'Ambient Light + Proximity', mfg: 'ams OSRAM', pn: 'TMD3725', qty: 1, cost: 1.2, supplier: 'DigiKey', leadTime: '2\u20134 wk' },
  { line: 13, subsystem: 'Sensors', part: 'Barometer (optional)', mfg: 'Bosch', pn: 'BMP390', qty: 1, cost: 1, supplier: 'DigiKey', leadTime: '2 wk', optional: true },
  { line: 14, subsystem: 'Sensors', part: 'Temp/Humidity (optional)', mfg: 'TI', pn: 'HDC3020', qty: 1, cost: 0.8, supplier: 'DigiKey', leadTime: '2 wk', optional: true },
  { line: 15, subsystem: 'Input', part: 'Touch/Squeeze Ring Ctrl', mfg: 'Azoteq', pn: 'IQS231', qty: 1, cost: 1.8, supplier: 'Distributor', leadTime: '6\u20138 wk' },
  { line: 16, subsystem: 'Haptics', part: 'Haptic Driver + LRA', mfg: 'TI', pn: 'DRV2605L + LRA', qty: 1, cost: 1.5, supplier: 'DigiKey', leadTime: '2\u20134 wk' },
  { line: 17, subsystem: 'I/O', part: 'Buttons + LEDs', mfg: 'C&K / Vishay', pn: 'TBD', qty: 2, cost: 0.2, supplier: 'DigiKey', leadTime: '2 wk' },
  { line: 18, subsystem: 'Power Path', part: 'Rail Switch / Sequencer', mfg: 'TI/ADI', pn: 'Load switches + GPIO EN', qty: 1, cost: 3, supplier: 'DigiKey', leadTime: '2\u20134 wk' },
  { line: 19, subsystem: 'Optional RF', part: 'LTE/GNSS modem (footprint)', mfg: 'Nordic', pn: 'nRF9161', qty: 1, cost: 12, supplier: 'Mouser', leadTime: '8\u201312 wk', optional: true },
  { line: 20, subsystem: 'Optional AI', part: 'Vision Accelerator (footprint)', mfg: 'BrainChip', pn: 'Akida AKD1000', qty: 0, cost: 15, supplier: 'Vendor', leadTime: '12+ wk', optional: true },
]
